DefaultContentLanguage = "ru"

[languages]
  [languages.ru]
    LanguageCode = "ru"
    baseURL = "https://nksoff.ru/"
    title = "Никита Слимов"
  [languages.en]
    LanguageCode = "en"
    baseURL = "https://en.nksoff.ru/"
    title = "Nikita Slimov"