DefaultContentLanguage = "ru"

[languages]
  [languages.ru]
    baseURL = "http://nksoff.ru/"
    title = "Никита Слимов"
  [languages.en]
    baseURL = "http://en.nksoff.ru/"
    title = "Nikita Slimov"